CREATE DATABASE IF NOT EXISTS incentives_db_test;
USE incentives_db_test;
-- Incentives
DROP TABLE IF EXISTS incentives;
CREATE TABLE IF NOT EXISTS incentives (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    -- id, code, expirydate, value, 
    -- another table owner 
    schema_type varchar(64) NOT NULL,
    type varchar(16) NOT NULL,
    start_date date NOT NULL,
    start_time time NOT NULL,
    stop_date date DEFAULT NULL,
    stop_time time DEFAULT NULL,
    code varchar(16) DEFAULT NULL,
    is_code_type_expression tinyint(1) unsigned DEFAULT 0,
    title varchar(128) DEFAULT NULL,
    description varchar(512) DEFAULT NULL,
    purpose varchar(32) DEFAULT NULL,
    channel varchar(32) DEFAULT NULL,
    value double(12, 2) DEFAULT NULL,
    minimum_order_value double(12, 2) DEFAULT NULL,
    maximum_order_value double(12, 2) DEFAULT NULL,
    maximum_incentive_amount double(12, 2) DEFAULT NULL,
    is_unlimited tinyint(1) unsigned DEFAULT 0,
    quantity int(10) unsigned DEFAULT 0,
    usage_counter int(10) unsigned DEFAULT 0,
    customer_quantity int(10) unsigned DEFAULT 0,
    daily_quantity int(10) unsigned DEFAULT 0,
    daily_usage_counter int(10) unsigned DEFAULT 0,
    daily_usage_counter_date date DEFAULT NULL,
    weekly_quantity int(10) unsigned DEFAULT 0,
    weekly_usage_counter int(10) unsigned DEFAULT 0,
    weekly_usage_counter_date date DEFAULT NULL,
    monthly_quantity int(10) unsigned DEFAULT 0,
    monthly_usage_counter int(10) unsigned DEFAULT 0,
    monthly_usage_counter_date date DEFAULT NULL,
    schedules varchar(512) DEFAULT NULL,
    payment_types varchar(255) DEFAULT NULL,
    bank_identification_numbers varchar(255) DEFAULT NULL,
    chains varchar(64) DEFAULT NULL,
    parent_vertical_types varchar(32) DEFAULT NULL,
    vertical_types varchar(512) DEFAULT NULL,
    expedition_types varchar(32) DEFAULT NULL,
    cities varchar(64) DEFAULT NULL,
    platforms varchar(32) DEFAULT NULL,
    is_new_customer_only tinyint(1) DEFAULT 0,
    is_new_customer_only_vertical_type tinyint(1) unsigned DEFAULT 0,
    is_new_customer_only_expedition_type tinyint(1) unsigned DEFAULT 0,
    is_unhealthy_customer_excluded tinyint(1) DEFAULT 0,
    sponsor_ratio double(5, 2) DEFAULT '100' COMMENT '0 => fully by vendor, 100 => fully by platform',
    tnc TEXT DEFAULT NULL,
    is_activated tinyint(1) unsigned DEFAULT 0,
    is_deleted tinyint(1) unsigned DEFAULT 0,
    has_customer tinyint(1) unsigned DEFAULT 0,
    has_vendor tinyint(1) unsigned DEFAULT 0,
    subscription_tier int(4) unsigned DEFAULT 0,
    created_by varchar(64) DEFAULT NULL,
    updated_by varchar(64) DEFAULT NULL,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY schema_type (schema_type),
    KEY type (type),
    KEY code (code)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;